### PR TITLE
react: extend React.Component, closes #13

### LINKED ISSUE #13: Use react-create-class instead maybe
https://facebook.github.io/react/docs/react-without-es6.html

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Instead of using `createClass`, extend `React.Component`.

This makes the React adapter identical to the Preact one, since Preact
is API compatible with React core.

I changed the preact adapter to refer to the react adapter, which works, but the assert messages will read `nanocomponent-adapters/react` when using the preact adapter. I can revert that if y'all think it's an issue. or the preact adapter could be removed entirely and the docs updated to explain that the react adapter can be used with preact as well.

### CODE REVIEW

**Comment by toddself** [comment]
I think just saying you can use the React one with the Preact one might be the best option here.

**Comment by goto-bus-stop** [comment]
Yeah, agreed. collapsed the react and preact sections into one. Also removed preact.js entirely, which does make it a breaking change!

**Comment by yoshuawuyts** [comment]
I'm cool with breaking changes on this module given it's still a bit
experimental. Neato changes! - Would this be good to merge, or is there
more that needs to happen? Thanks!

**Comment by goto-bus-stop** [comment]
Good to go from my manual tests!

**Pull request merged**
